<a href="https://colab.research.google.com/github/i-SanMartin/FastAI/blob/main/05_Pet_Breeds/Loss_Func.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from matplotlib import pyplot
import numpy as np
import torch

Softmax

In [2]:
#Generate random results
probs = np.random.rand(4,3)*5
probs

array([[0.38938576, 3.80871909, 3.93630072],
       [0.07628872, 2.62646151, 1.74608054],
       [1.40766794, 1.47783707, 3.82721585],
       [1.95441974, 2.90794841, 0.88088106]])

In [3]:
#Apply softmax
y = np.array(list(np.exp(i)/np.sum(np.exp(i)) for i in probs))
y

array([[0.01509317, 0.46108195, 0.52382488],
       [0.05230022, 0.66993007, 0.27776971],
       [0.07511192, 0.08057178, 0.8443163 ],
       [0.2540233 , 0.65915233, 0.08682437]])

In [4]:
#Check results
torch.softmax(torch.tensor(probs),dim=1)

tensor([[0.0151, 0.4611, 0.5238],
        [0.0523, 0.6699, 0.2778],
        [0.0751, 0.0806, 0.8443],
        [0.2540, 0.6592, 0.0868]], dtype=torch.float64)

Log Likelihood

In [5]:
#Create targets
target = np.array(np.trunc(np.random.rand(4)*3,),dtype=np.int)
target

array([1, 0, 1, 1])

In [6]:
#Calculate Loss
idx = range(3)
loss = np.array([-np.log(y[id, targ]) for id, targ in enumerate(target)])
loss

array([0.77417948, 2.95075473, 2.51860687, 0.41680061])

In [7]:
#Check results
torch.nn.CrossEntropyLoss(reduction='none')(torch.tensor(probs),torch.tensor(target))

tensor([0.7742, 2.9508, 2.5186, 0.4168], dtype=torch.float64)

In [8]:
np.mean(loss)

1.6650854217598214

In [10]:
torch.nn.CrossEntropyLoss()(torch.tensor(probs),torch.tensor(target))

tensor(1.6651, dtype=torch.float64)