<a href="https://colab.research.google.com/github/i-SanMartin/FastAI/blob/main/05_Pet_Breeds/Loss_Func.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from matplotlib import pyplot
import numpy as np
import torch

Softmax

In [2]:
cat = np.random.rand(4,3)*5
cat

array([[1.29757135, 3.24767612, 4.585921  ],
       [4.23811966, 2.39050145, 2.48671708],
       [0.36254123, 4.90293229, 2.82316707],
       [0.00743966, 3.5957067 , 4.42194808]])

In [3]:
y = np.array(list(np.exp(i)/np.sum(np.exp(i)) for i in cat))
y

array([[0.02871251, 0.20183241, 0.76945508],
       [0.75123437, 0.11840364, 0.13036199],
       [0.009395  , 0.88056944, 0.11003556],
       [0.00834637, 0.30189943, 0.6897542 ]])

In [4]:
torch.softmax(torch.tensor(cat),dim=1)

tensor([[0.0287, 0.2018, 0.7695],
        [0.7512, 0.1184, 0.1304],
        [0.0094, 0.8806, 0.1100],
        [0.0083, 0.3019, 0.6898]], dtype=torch.float64)

Log Likelihood

In [23]:
#Create targets
target = np.array(np.trunc(np.random.rand(4)*3,),dtype=np.int)
target

array([0, 0, 2, 2])

In [33]:
idx = range(3)
loss = np.array([1 - y[id, targ] for id, targ in enumerate(target)])
loss

array([0.97128749, 0.24876563, 0.88996444, 0.3102458 ])