<a href="https://colab.research.google.com/github/i-SanMartin/FastAI/blob/main/05_Pet_Breeds/Loss_Func.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
from matplotlib import pyplot
import numpy as np
import torch

Softmax

In [52]:
cat = np.random.rand(4,3)*5
cat

array([[0.08714175, 3.31313011, 2.65621174],
       [3.54447486, 1.36973905, 4.38078275],
       [0.02051452, 2.46805459, 4.9916172 ],
       [0.29530254, 3.22034933, 4.89437923]])

In [66]:
y = np.array(list(np.exp(i)/np.sum(np.exp(i)) for i in cat))
y

array([[0.02548931, 0.64178136, 0.33272932],
       [0.29227215, 0.03321327, 0.67451458],
       [0.00637976, 0.07374925, 0.91987099],
       [0.00840141, 0.15656115, 0.83503744]])

In [65]:
torch.softmax(torch.tensor(cat),dim=1)

tensor([[0.0255, 0.6418, 0.3327],
        [0.2923, 0.0332, 0.6745],
        [0.0064, 0.0737, 0.9199],
        [0.0084, 0.1566, 0.8350]], dtype=torch.float64)

Log Likelihood

In [84]:
#Create targets
targ = np.trunc(np.random.rand(4)*3)
targ

array([1., 2., 1., 2.])